language: objective-c
matrix:
  include:
    - osx_image: xcode7.3
env:
  global:
    - LC_CTYPE=en_US.UTF-8
git:
  submodules: false
branches:
  only:
    - master
cache:
  - bundler
  - cocoapods
before_install:
  - git submodule update --init --recursive
script:
  - pod lib lint
  - set -o pipefail
  - xcodebuild test -workspace meditalk.xcworkspace -scheme meditalk_iOS -configuration Debug -sdk iphonesimulator -destination "platform=iOS Simulator,name=iPhone 6s" | xcpretty -c
notifications:
  email: false
